### ISSUE TITLE
install of requirements fails

### ISSUE THREAD

**Issue by ghost** [Arzaroth/CelestiaSunrise#2]
what did i do wrong?

git clone https://github.com/Arzaroth/CelestiaSunrise.git
Nach »CelestiaSunrise« wird geklont
remote: Counting objects: 491, done.
remote: Total 491 (delta 0), reused 0 (delta 0), pack-reused 491
Objekte werden empfangen: 100% (491/491), 152.80 KiB | 0 bytes/s, done.
Unterschiede werden aufgelöst: 100% (327/327), done.
Verbundenheit wird überprüft … Fertig.
amon@c18:~$ cd CelestiaSunrise/
amon@c18:~/CelestiaSunrise$ sudo pip install -r requirements.txt 
Requirement already satisfied (use --upgrade to upgrade): docopt==0.6.2 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Downloading/unpacking RapidXml==1.0.6 (from -r requirements.txt (line 2))
  Downloading RapidXml-1.0.6.tar.gz
  Running setup.py (path:/tmp/pip_build_root/RapidXml/setup.py) egg_info for package RapidXml

```
no previously-included directories found matching 'test'
```

Requirement already satisfied (use --upgrade to upgrade): six==1.9.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Installing collected packages: RapidXml
  Running setup.py install for RapidXml
    building '_rapidxml' extension
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DMAJOR_VERSION=1 -DMINOR_VERSION=0 -Irapidxml/c_ext/inc/ -Irapidxml/c_ext/inc/rapidxml-1.13/ -I/usr/include/python2.7 -c rapidxml/c_ext/src/common.cpp -o build/temp.linux-x86_64-2.7/rapidxml/c_ext/src/common.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    rapidxml/c_ext/src/common.cpp:10:20: fatal error: Python.h: Datei oder Verzeichnis nicht gefunden
     #include <Python.h>
                        ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/RapidXml/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-OSyI5G-record/install-record.txt --single-version-externally-managed --compile:
    running install

running build

running build_py

creating build

creating build/lib.linux-x86_64-2.7

creating build/lib.linux-x86_64-2.7/rapidxml

copying rapidxml/rapidxml.py -> build/lib.linux-x86_64-2.7/rapidxml

copying rapidxml/**init**.py -> build/lib.linux-x86_64-2.7/rapidxml

running build_ext

building '_rapidxml' extension

creating build/temp.linux-x86_64-2.7

creating build/temp.linux-x86_64-2.7/rapidxml

creating build/temp.linux-x86_64-2.7/rapidxml/c_ext

creating build/temp.linux-x86_64-2.7/rapidxml/c_ext/src

x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DMAJOR_VERSION=1 -DMINOR_VERSION=0 -Irapidxml/c_ext/inc/ -Irapidxml/c_ext/inc/rapidxml-1.13/ -I/usr/include/python2.7 -c rapidxml/c_ext/src/common.cpp -o build/temp.linux-x86_64-2.7/rapidxml/c_ext/src/common.o

cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]

rapidxml/c_ext/src/common.cpp:10:20: fatal error: Python.h: Datei oder Verzeichnis nicht gefunden

 #include <Python.h>

```
                ^
```

compilation terminated.

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

---

Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;**file**='/tmp/pip_build_root/RapidXml/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-OSyI5G-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/RapidXml
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.4', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pip/**init**.py", line 235, in main
    return command.main(cmd_args)
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 42: ordinal not in range(128)

**Comment by Arzaroth** [comment]
Python development headers are missing. If your distrib is apt-based:
sudo apt-get install python-dev

yum-based:
sudo yum install python-devel

And so on...

**Comment by ghost** [comment]
oh, silly me ^^

**Comment by ghost** [comment]
pip is okay now install still fails:

sudo pip install -r requirements.txt
Requirement already satisfied (use --upgrade to upgrade): docopt==0.6.2 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1))
Downloading/unpacking RapidXml==1.0.6 (from -r requirements.txt (line 2))
  Downloading RapidXml-1.0.6.tar.gz
  Running setup.py (path:/tmp/pip_build_root/RapidXml/setup.py) egg_info for package RapidXml

```
no previously-included directories found matching 'test'
```

Requirement already satisfied (use --upgrade to upgrade): six==1.9.0 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3))
Installing collected packages: RapidXml
  Found existing installation: RapidXml 1.0.7
    Uninstalling RapidXml:
      Successfully uninstalled RapidXml
  Running setup.py install for RapidXml
    building '_rapidxml' extension
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DMAJOR_VERSION=1 -DMINOR_VERSION=0 -Irapidxml/c_ext/inc/ -Irapidxml/c_ext/inc/rapidxml-1.13/ -I/usr/include/python2.7 -c rapidxml/c_ext/src/common.cpp -o build/temp.linux-x86_64-2.7/rapidxml/c_ext/src/common.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DMAJOR_VERSION=1 -DMINOR_VERSION=0 -Irapidxml/c_ext/inc/ -Irapidxml/c_ext/inc/rapidxml-1.13/ -I/usr/include/python2.7 -c rapidxml/c_ext/src/rapidxml_module.cpp -o build/temp.linux-x86_64-2.7/rapidxml/c_ext/src/rapidxml_module.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    rapidxml/c_ext/src/rapidxml_module.cpp: In function ‘void init_rapidxml()’:
    rapidxml/c_ext/src/rapidxml_module.cpp:105:57: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
                                                   NULL, NULL);
                                                             ^
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DMAJOR_VERSION=1 -DMINOR_VERSION=0 -Irapidxml/c_ext/inc/ -Irapidxml/c_ext/inc/rapidxml-1.13/ -I/usr/include/python2.7 -c rapidxml/c_ext/src/base_object.cpp -o build/temp.linux-x86_64-2.7/rapidxml/c_ext/src/base_object.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    rapidxml/c_ext/src/base_object.cpp:194:1: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
     };
     ^
    rapidxml/c_ext/src/base_object.cpp:194:1: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
    rapidxml/c_ext/src/base_object.cpp:194:1: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
    rapidxml/c_ext/src/base_object.cpp:194:1: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
    rapidxml/c_ext/src/base_object.cpp:194:1: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
    rapidxml/c_ext/src/base_object.cpp:194:1: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DMAJOR_VERSION=1 -DMINOR_VERSION=0 -Irapidxml/c_ext/inc/ -Irapidxml/c_ext/inc/rapidxml-1.13/ -I/usr/include/python2.7 -c rapidxml/c_ext/src/node_object.cpp -o build/temp.linux-x86_64-2.7/rapidxml/c_ext/src/node_object.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    rapidxml/c_ext/src/node_object.cpp:475:1: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
     };
     ^
    rapidxml/c_ext/src/node_object.cpp:475:1: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
    rapidxml/c_ext/src/node_object.cpp:475:1: warning: deprecated conversion from string constant to ‘char_’ [-Wwrite-strings]
    rapidxml/c_ext/src/node_object.cpp:475:1: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DMAJOR_VERSION=1 -DMINOR_VERSION=0 -Irapidxml/c_ext/inc/ -Irapidxml/c_ext/inc/rapidxml-1.13/ -I/usr/include/python2.7 -c rapidxml/c_ext/src/attribute_object.cpp -o build/temp.linux-x86_64-2.7/rapidxml/c_ext/src/attribute_object.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DMAJOR_VERSION=1 -DMINOR_VERSION=0 -Irapidxml/c_ext/inc/ -Irapidxml/c_ext/inc/rapidxml-1.13/ -I/usr/include/python2.7 -c rapidxml/c_ext/src/document_object.cpp -o build/temp.linux-x86_64-2.7/rapidxml/c_ext/src/document_object.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DMAJOR_VERSION=1 -DMINOR_VERSION=0 -Irapidxml/c_ext/inc/ -Irapidxml/c_ext/inc/rapidxml-1.13/ -I/usr/include/python2.7 -c rapidxml/c_ext/src/nodeiterator_object.cpp -o build/temp.linux-x86_64-2.7/rapidxml/c_ext/src/nodeiterator_object.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DMAJOR_VERSION=1 -DMINOR_VERSION=0 -Irapidxml/c_ext/inc/ -Irapidxml/c_ext/inc/rapidxml-1.13/ -I/usr/include/python2.7 -c rapidxml/c_ext/src/attributeiterator_object.cpp -o build/temp.linux-x86_64-2.7/rapidxml/c_ext/src/attributeiterator_object.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
    c++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/rapidxml/c_ext/src/common.o build/temp.linux-x86_64-2.7/rapidxml/c_ext/src/rapidxml_module.o build/temp.linux-x86_64-2.7/rapidxml/c_ext/src/base_object.o build/temp.linux-x86_64-2.7/rapidxml/c_ext/src/node_object.o build/temp.linux-x86_64-2.7/rapidxml/c_ext/src/attribute_object.o build/temp.linux-x86_64-2.7/rapidxml/c_ext/src/document_object.o build/temp.linux-x86_64-2.7/rapidxml/c_ext/src/nodeiterator_object.o build/temp.linux-x86_64-2.7/rapidxml/c_ext/src/attributeiterator_object.o -o build/lib.linux-x86_64-2.7/_rapidxml.so

```
no previously-included directories found matching 'test'
```

Successfully installed RapidXml
Cleaning up...
amon@c18:~/CelestiaSunrise$ python3.4 setup.py install --user
running install
running bdist_egg
running egg_info
writing requirements to CelestiaSunrise.egg-info/requires.txt
writing top-level names to CelestiaSunrise.egg-info/top_level.txt
writing CelestiaSunrise.egg-info/PKG-INFO
writing dependency_links to CelestiaSunrise.egg-info/dependency_links.txt
reading manifest file 'CelestiaSunrise.egg-info/SOURCES.txt'
writing manifest file 'CelestiaSunrise.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/src
creating build/bdist.linux-x86_64/egg/src/utility
copying build/lib/src/utility/defaultordereddict.py -> build/bdist.linux-x86_64/egg/src/utility
copying build/lib/src/utility/xxtea.py -> build/bdist.linux-x86_64/egg/src/utility
copying build/lib/src/utility/utility.py -> build/bdist.linux-x86_64/egg/src/utility
copying build/lib/src/utility/**init**.py -> build/bdist.linux-x86_64/egg/src/utility
copying build/lib/src/utility/enum.py -> build/bdist.linux-x86_64/egg/src/utility
copying build/lib/src/utility/gluid.py -> build/bdist.linux-x86_64/egg/src/utility
copying build/lib/src/utility/tkvardescriptor.py -> build/bdist.linux-x86_64/egg/src/utility
creating build/bdist.linux-x86_64/egg/src/xml
copying build/lib/src/xml/**init**.py -> build/bdist.linux-x86_64/egg/src/xml
copying build/lib/src/xml/xmlhandler.py -> build/bdist.linux-x86_64/egg/src/xml
copying build/lib/src/**init**.py -> build/bdist.linux-x86_64/egg/src
creating build/bdist.linux-x86_64/egg/src/shell
copying build/lib/src/shell/ponyshell.py -> build/bdist.linux-x86_64/egg/src/shell
copying build/lib/src/shell/set.py -> build/bdist.linux-x86_64/egg/src/shell
copying build/lib/src/shell/docopt_utils.py -> build/bdist.linux-x86_64/egg/src/shell
copying build/lib/src/shell/**init**.py -> build/bdist.linux-x86_64/egg/src/shell
copying build/lib/src/shell/show.py -> build/bdist.linux-x86_64/egg/src/shell
copying build/lib/src/savemanager.py -> build/bdist.linux-x86_64/egg/src
creating build/bdist.linux-x86_64/egg/src/gui
copying build/lib/src/gui/poniesframe.py -> build/bdist.linux-x86_64/egg/src/gui
copying build/lib/src/gui/scrollframe.py -> build/bdist.linux-x86_64/egg/src/gui
copying build/lib/src/gui/ponygui.py -> build/bdist.linux-x86_64/egg/src/gui
copying build/lib/src/gui/**init**.py -> build/bdist.linux-x86_64/egg/src/gui
copying build/lib/src/gui/loading.py -> build/bdist.linux-x86_64/egg/src/gui
copying build/lib/src/gui/currenciesframe.py -> build/bdist.linux-x86_64/egg/src/gui
copying build/lib/src/gui/basegui.py -> build/bdist.linux-x86_64/egg/src/gui
copying build/lib/src/gui/zonesframe.py -> build/bdist.linux-x86_64/egg/src/gui
copying build/lib/src/gui/missingponiesframe.py -> build/bdist.linux-x86_64/egg/src/gui
copying build/lib/src/gui/gui.py -> build/bdist.linux-x86_64/egg/src/gui
byte-compiling build/bdist.linux-x86_64/egg/src/utility/defaultordereddict.py to defaultordereddict.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/utility/xxtea.py to xxtea.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/utility/utility.py to utility.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/utility/**init**.py to **init**.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/utility/enum.py to enum.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/utility/gluid.py to gluid.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/utility/tkvardescriptor.py to tkvardescriptor.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/xml/**init**.py to **init**.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/xml/xmlhandler.py to xmlhandler.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/**init**.py to **init**.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/shell/ponyshell.py to ponyshell.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/shell/set.py to set.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/shell/docopt_utils.py to docopt_utils.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/shell/**init**.py to **init**.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/shell/show.py to show.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/savemanager.py to savemanager.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/gui/poniesframe.py to poniesframe.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/gui/scrollframe.py to scrollframe.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/gui/ponygui.py to ponygui.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/gui/**init**.py to **init**.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/gui/loading.py to loading.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/gui/currenciesframe.py to currenciesframe.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/gui/basegui.py to basegui.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/gui/zonesframe.py to zonesframe.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/gui/missingponiesframe.py to missingponiesframe.cpython-34.pyc
byte-compiling build/bdist.linux-x86_64/egg/src/gui/gui.py to gui.cpython-34.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.4/CelestiaSunrise.py -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/CelestiaSunrise.py to 755
copying CelestiaSunrise.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying CelestiaSunrise.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying CelestiaSunrise.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying CelestiaSunrise.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying CelestiaSunrise.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/CelestiaSunrise-v1.1.0-py3.4.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing CelestiaSunrise-v1.1.0-py3.4.egg
Removing /home/amon/.local/lib/python3.4/site-packages/CelestiaSunrise-v1.1.0-py3.4.egg
Copying CelestiaSunrise-v1.1.0-py3.4.egg to /home/amon/.local/lib/python3.4/site-packages
CelestiaSunrise v1.1.0 is already the active version in easy-install.pth
Installing CelestiaSunrise.py script to /home/amon/.local/bin

Installed /home/amon/.local/lib/python3.4/site-packages/CelestiaSunrise-v1.1.0-py3.4.egg
Processing dependencies for CelestiaSunrise==v1.1.0
Searching for RapidXml==1.0.6
Reading https://pypi.python.org/simple/RapidXml/
Best match: RapidXml 1.0.6
Downloading https://pypi.python.org/packages/source/R/RapidXml/RapidXml-1.0.6.tar.gz#md5=f1039f6848f9e2bfed01410d1ee9f39a
Processing RapidXml-1.0.6.tar.gz
Writing /tmp/easy_install-ulxd3x5r/RapidXml-1.0.6/setup.cfg
Running RapidXml-1.0.6/setup.py -q bdist_egg --dist-dir /tmp/easy_install-ulxd3x5r/RapidXml-1.0.6/egg-dist-tmp-j58zmk59
no previously-included directories found matching 'test'
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
rapidxml/c_ext/src/common.cpp:10:20: fatal error: Python.h: Datei oder Verzeichnis nicht gefunden
 #include <Python.h>
                    ^
compilation terminated.
error: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by ghost** [comment]
needed phython3.4-dev as well. program now runs.
